# Generated by Django 5.0.4 on 2024-04-30 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tirle',
            new_name='title',
        ),
    ]
